server:
  port: 8082
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true