server:
  port: 8083
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-a:
      path: /get/**
      serviceId: consumer
    api-b:
      path: /test/**
      serviceId: provider
  ignored-services: "*"
  prefix: /api/v1/demo