server:
  port: 8085
spring:
  application:
    name: config-server
  http:
    encoding:
      charset: utf-8
      force: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rice1001/spring-cloud-config.git
          search-paths: /config-repo
          skip-ssl-validation: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka